#:schema ../../api/generated/v2/language.json
direction = "ltr"
id = "isv_l"
locale = "isv-Latn"

[name]
en = "Interslavic (Latin)"
endonym = "Medžuslovjansky (latinica)"
tok = "toki Mesulojanki (sitelen Lasina)"
